export const atletas_disciplina = [
  {
    deporte: "AGUAS ABIERTAS",
    categoria_usuario: "ATLETA",
    nombre: "RUTHSELI GUADALUPE ",
    apellido: "APONTE TERAN ",
    sexo: "F",
    num_pasaporte: 166626063,
    num_cedula: 16646063,
    vencimiento_pasaporte: "16/03/2032",
  },
  {
    deporte: "BALONMANO",
    categoria_usuario: "ATLETA",
    nombre: "SOFIA CRISTINA",
    apellido: "PASCUZZO ROTONDARO",
    sexo: "F",
    num_pasaporte: 128032824,
    num_cedula: 12842824,
    vencimiento_pasaporte: "23/08/2026",
  },
  {
    deporte: "FUTBOL ",
    categoria_usuario: "ATLETA",
    nombre: "DIEGO ARMANDO",
    apellido: "VERA DELGADO",
    sexo: "M",
    num_pasaporte: 159728224,
    num_cedula: 15948224,
    vencimiento_pasaporte: "09/04/2026",
  },
  {
    deporte: "LUCHA",
    categoria_usuario: "ATLETA",
    nombre: "DANIEL ALEJANDRO",
    apellido: "JUAREZ RODRIGUEZ",
    sexo: "M",
    num_pasaporte: 131019711,
    num_cedula: 13149711,
    vencimiento_pasaporte: "25/01/2023",
  },
  {
    deporte: "RUGBY",
    categoria_usuario: "ENTRENADOR",
    nombre: "MIGUEL ANGEL",
    apellido: "JUAREZ MARTINEZ",
    sexo: "M",
    num_pasaporte: 106416592,
    num_cedula: 10646592,
    vencimiento_pasaporte: "19/08/2021",
  },
  {
    deporte: "SKATEBOARDING",
    categoria_usuario: "DELEGADO",
    nombre: "CARLOS ANTONIO",
    apellido: "CHACÓN VILLEGAS",
    sexo: "M",
    num_pasaporte: 157195969,
    num_cedula: 15745969,
    vencimiento_pasaporte: "10/07/2024",
  },
  {
    deporte: "SURF",
    categoria_usuario: "ATLETA",
    nombre: "FRANNELLY JUVILETH ",
    apellido: "POLANCO GARCES ",
    sexo: "F",
    num_pasaporte: 169607346,
    num_cedula: 16947346,
    vencimiento_pasaporte: "26/07/2032",
  },
  {
    deporte: "TENIS",
    categoria_usuario: "ATLETA",
    nombre: "ISKARY",
    apellido: "AGUILAR",
    sexo: "F",
    num_pasaporte: 142989599,
    num_cedula: 14249599,
    vencimiento_pasaporte: "02/05/2022",
  },
  {
    deporte: "VELA",
    categoria_usuario: "ATLETA",
    nombre: "YARKETZI YAMIRET",
    apellido: "MORENO RENGIFO ",
    sexo: "F",
    num_pasaporte: 169968951,
    num_cedula: 16948951,
    vencimiento_pasaporte: "09/08/2032",
  },
  {
    deporte: "VOLEIBOL",
    categoria_usuario: "ATLETA",
    nombre: "LUZ ALEXANDRA",
    apellido: "COLINA MIQUELENA ",
    sexo: "F",
    num_pasaporte: 166687622,
    num_cedula: 16647622,
    vencimiento_pasaporte: "22/03/2023",
  },
  {
    deporte: "COV",
    categoria_usuario: "ATLETA",
    nombre: "GABRIELA",
    apellido: "GAMEZ",
    sexo: "F",
    num_pasaporte: 119314612,
    num_cedula: 11944612,
    vencimiento_pasaporte: "26/03/2020",
  },
  {
    deporte: "MINISTERIO IND",
    categoria_usuario: "ATLETA",
    nombre: "MILANGELA COROMOTO",
    apellido: "TOVAR HOSPEDALES",
    sexo: "F",
    num_pasaporte: 169607278,
    num_cedula: 16947278,
    vencimiento_pasaporte: "26/07/2032",
  },
  {
    deporte: "PRENSA COV",
    categoria_usuario: "ATLETA",
    nombre: "MIRAIDY JACKELIN",
    apellido: "SUAREZ RUIZ",
    sexo: "F",
    num_pasaporte: 120052589,
    num_cedula: 12042589,
    vencimiento_pasaporte: "07/05/2020",
  },
  {
    deporte: "PRENSA MIN",
    categoria_usuario: "ATLETA",
    nombre: "ANGLYS",
    apellido: "NOGUERA",
    sexo: "F",
    num_pasaporte: "057921332",
    num_cedula: "05421332",
    vencimiento_pasaporte: "08/05/2017",
  },
  {
    deporte: "PRENSA VTV",
    categoria_usuario: "ATLETA",
    nombre: "HERNAIRY TERESA",
    apellido: "VARGAS",
    sexo: "F",
    num_pasaporte: 122130179,
    num_cedula: 12240179,
    vencimiento_pasaporte: "13/09/2020",
  },
  {
    deporte: "ATLETISMO ",
    categoria_usuario: "ATLETA",
    nombre: " MAIKELLY MICHELLE",
    apellido: "CEDEÑO BRACHO ",
    sexo: "F",
    num_pasaporte: 171584992,
    num_cedula: 17144992,
    vencimiento_pasaporte: "25/09/2032",
  },
  {
    deporte: "NATACION ",
    categoria_usuario: "ATLETA",
    nombre: " DIXON ANDRES ",
    apellido: "SILVA ANDUEZA  ",
    sexo: "M",
    num_pasaporte: 160713039,
    num_cedula: 16043039,
    vencimiento_pasaporte: "25/08/2031",
  },
  {
    deporte: "KARATE DO ",
    categoria_usuario: "ATLETA",
    nombre: " JESUS RICARDO",
    apellido: "GUARECUCO CASTILLO ",
    sexo: "M",
    num_pasaporte: 171202186,
    num_cedula: 17142186,
    vencimiento_pasaporte: "12/09/2032",
  },
  {
    deporte: "ESGRIMA ",
    categoria_usuario: "ATLETA",
    nombre: " RONAL ANTONIO",
    apellido: "TIMAURE DORANTES ",
    sexo: "M",
    num_pasaporte: 171574546,
    num_cedula: 17144546,
    vencimiento_pasaporte: "25/09/2032",
  },
  {
    deporte: "JUDO ",
    categoria_usuario: "ATLETA",
    nombre: " JESUS MANUEL",
    apellido: "BARRIOS BATISTA ",
    sexo: "M",
    num_pasaporte: 123143516,
    num_cedula: 12343516,
    vencimiento_pasaporte: "06/08/2020",
  },
  {
    deporte: "BOWLING ",
    categoria_usuario: "ATLETA",
    nombre: " RAINNER JOSE",
    apellido: "SEIJAS PALACIOS ",
    sexo: "M",
    num_pasaporte: 79606930,
    num_cedula: 7964930,
    vencimiento_pasaporte: "08/06/2020",
  },
  {
    deporte: "LEV DE PESAS ",
    categoria_usuario: "ATLETA",
    nombre: " DAIRO JOSE",
    apellido: "LOPEZ HERNANDEZ ",
    sexo: "M",
    num_pasaporte: 150342887,
    num_cedula: 15042887,
    vencimiento_pasaporte: "10/06/2027",
  },
  {
    deporte: "CICLISMO FREESTYLE",
    categoria_usuario: "ATLETA",
    nombre: " SANDERS ALEJANDRO",
    apellido: "PEÑALOZA DIAZ ",
    sexo: "M",
    num_pasaporte: 160713055,
    num_cedula: 16043055,
    vencimiento_pasaporte: "24/08/2031",
  },
  {
    deporte: "CICLISMO RUTA ",
    categoria_usuario: "ATLETA",
    nombre: " WILMER DARCI",
    apellido: "BRACHO CASTELLANO ",
    sexo: "M",
    num_pasaporte: 107582416,
    num_cedula: 10742416,
    vencimiento_pasaporte: "08/10/2019",
  },
  {
    deporte: "REMO",
    categoria_usuario: "DELEGADO",
    nombre: " ELI SAUL",
    apellido: "GONZALEZ DELGADO ",
    sexo: "M",
    num_pasaporte: 166799637,
    num_cedula: 16649637,
    vencimiento_pasaporte: "27/03/2032",
  },
  {
    deporte: "CANOTAJE VELOCIDAD ",
    categoria_usuario: "ENTRENADOR",
    nombre: " OCTAVIO JOSE",
    apellido: "SANCHEZ MORENO ",
    sexo: "M",
    num_pasaporte: 169607320,
    num_cedula: 16947320,
    vencimiento_pasaporte: "26/07/2032",
  },
  {
    deporte: "CICLISMO RACING",
    categoria_usuario: "ENTRENADOR",
    nombre: "JOSE GREGORIO",
    apellido: "ORTEGA",
    sexo: "M",
    num_pasaporte: 144398698,
    num_cedula: 14448698,
    vencimiento_pasaporte: "21/04/2027",
  },
  {
    deporte: "TENIS CAMPO",
    categoria_usuario: "ENTRENADOR",
    nombre: " CHRYSTOPHER ALONZO",
    apellido: "TIMAURE PATIKA ",
    sexo: "M",
    num_pasaporte: 167604642,
    num_cedula: 16744642,
    vencimiento_pasaporte: "20/04/2032",
  },
  {
    deporte: "PATINAJE ",
    categoria_usuario: "ATLETA",
    nombre: " ALI ALEXANDER ",
    apellido: "BARRANCO BERNAL  ",
    sexo: "M",
    num_pasaporte: 124194843,
    num_cedula: 12444843,
    vencimiento_pasaporte: "03/09/2020",
  },
  {
    deporte: "CANOTAJE SLALOM ",
    categoria_usuario: "ATLETA",
    nombre: " VICENTE ANTONIO",
    apellido: "DUQUE LEÓN ",
    sexo: "M",
    num_pasaporte: 157555965,
    num_cedula: 15745965,
    vencimiento_pasaporte: "14/08/2024",
  },
  {
    deporte: "GOLF ",
    categoria_usuario: "ATLETA",
    nombre: " ROBERT JESUS",
    apellido: "PEREZ INSAUSTI ",
    sexo: "M",
    num_pasaporte: 159815610,
    num_cedula: 15945610,
    vencimiento_pasaporte: "20/06/2031",
  },
  {
    deporte: "TRIATLON ",
    categoria_usuario: "ATLETA",
    nombre: " ROSDEL JOSE",
    apellido: "RAMOS PATIÑO ",
    sexo: "M",
    num_pasaporte: 159815597,
    num_cedula: 15945597,
    vencimiento_pasaporte: "20/06/2031",
  },
  {
    deporte: "CLAVADOS ",
    categoria_usuario: "ATLETA",
    nombre: " JEYKER MOISES",
    apellido: "RIVERO DOMINGUEZ ",
    sexo: "M",
    num_pasaporte: 168329216,
    num_cedula: 16849216,
    vencimiento_pasaporte: "15/05/2032",
  },
  {
    deporte: "POLO ACUATICO FEM ",
    categoria_usuario: "ATLETA",
    nombre: " WUINDER ALBERTO",
    apellido: "MUÑOZ CALDERA ",
    sexo: "M",
    num_pasaporte: 159815513,
    num_cedula: 15945513,
    vencimiento_pasaporte: "20/06/2031",
  },
];

export const add_aditional_data_fake = () => {
  return atletas_disciplina.map((data) => {
    // * esta variable la usamos para determinar datos de prueba
    const variable_par = data.num_pasaporte % 2 == 0;
    const size_short = variable_par ? "M" : "L";

    let size_pants, size_shoes, size_jacket, num_vaccine;
    if (data.sexo == "M") {
      size_pants = variable_par ? "34" : "36";
      size_shoes = variable_par ? "43" : "44";
      size_jacket = variable_par ? "L" : "XL";
      num_vaccine = variable_par ? 1 : 2;
    } else {
      size_pants = variable_par ? "12" : "14";
      size_shoes = variable_par ? "36" : "37";
      size_jacket = variable_par ? "S" : "M";
      num_vaccine = variable_par ? 3 : 4;
    }

    return {
      ...data,
      num_certificado_nacimiento: Math.round(data.num_cedula / 3 + 0.234),
      pasaporte_status: variable_par ? "VIGENTE" : "VENCIDO",
      disciplina: "------",
      talla_pantalon: size_pants,
      talla_short: size_short,
      talla_calzado: size_shoes,
      talla_chaqueta: size_jacket,
      vacunado: variable_par ? "Si" : "No",
      num_vacunas: num_vaccine,
    };
  });
};
